---
title: "First Knit"
author: "Your Name"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  I attended high school at both Lancaster High School and Antelope Valley High School. But I graduated from Antelope Valley High School in 2019.English is easier for me than math class. I seem to struggle in math classes generally.I did the best in my English classes.English classes are generally easier for me than all other subjects.

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  I have an HP laptop at home. On a scale of one through ten, I would rate myself a 4 or 5 at computor knowledge.My internet connection is usually pretty stable at home though sometimes it will crash or I will have to step into a different room for better connection.
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer 
The name that I prefer everybody to call me is Viviana. It's my birth name so it's pretty hard to mess up and call me the wrong thing.
  
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer 
My main goal in live is to have a job that I enjoy and make enough money to live a comfortable life.I'm not sure which college subject would be the greatest interest to me. I am trying to achieve a degree in Psychology.
  
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  The only foreign country that I have been to is Mexico. In the future I'd like to go to Iceland and maybe Australia.I have never been in the military and if i got drafted I would probably choose the air force since it seems the most fun.
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  I have taken Math 115 in the past but got a D so I needed to take it again this semester. In order to not upset my future plans I need at least a C but preferable a B or higher to raise my GPA. My plan is to graduate and eventually get my Bachelors in Psychology.
   
 






  




